image: python:3.9 

pages:
  script:
    - mkdir public
    - cp -r docs/* public
    - pip install markdown
    - cd public/classes/exercises && for i in *.md; do python -m markdown ${i} -f ${i::-2}html; done
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  after_script:
#    - for i in $(ls metalsite |grep "ex"); do mv metalsite/${i}/index.html public/classes/exercises/${i}.html; echo "</body></html>" >> public/classes/exercises/${i}.html; done
    - sed -i '1 i<html>\n<head>\n<link rel="stylesheet" type="text/css" href="styles/main.css">\n</head>\n<body>\n' public/classes/exercises/*.html
    - sed -i 's|<body>|<body><header>\n<div class="container">\n<h1>FE2021</h1>\n<h2>Fundamentos de Epidemiologia 2021</h2>\n</div>\n</header>\n<div class="container">\n<section id="main_content">|' public/classes/exercises/*.html
    - sed -i 's|</body>|</section>\n</div>\n</body>|' public/classes/exercises/*.html
    - mv html/styles public/classes/exercises/styles
    - mv html/images public/classes/exercises/images
  artifacts:
    paths:
    - public
  only:
  - master
